version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: voting
      POSTGRES_PASSWORD: voting
      POSTGRES_DB: voting
    ports:
      - "5432:5432"
